**Data Manipulation**

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('/5DATA002W.2 Coursework Dataset(25012025v6.0).csv')

In [5]:
#displaying first five rows
df.head()

Patient_ID  Month_of_Birth   Age     Sex   Occupation T_Stage N_Stage  \
0      A0012              12  68.0  Female     Teaching      T1      N1   
1      A0013              12  50.0  Female      Medical      T2      N2   
2      A0014              11  58.0  Female  Engineering      T3      N3   
3      A0015               3  58.0  Female   Technology      T1      N1   
4      A0016               1  47.0  Female   Multimedia      T2      N1   

  6th_Stage             Differentiated  Grade   A_Stage  Tumor_Size  \
0       IIA      Poorly differentiated      3  Regional         4.0   
1      IIIA  Moderately differentiated      2  Regional        35.0   
2      IIIC  Moderately differentiated      2  Regional        63.0   
3       IIA      Poorly differentiated      3  Regional        18.0   
4       IIB      Poorly differentiated      3  Regional        41.0   

  Estrogen_Status Progesterone_Status  Regional_Node_Examined  \
0        Positive            Positive                    24.0   
1        Positive            Positive                    14.0   
2        Positive            Positive                    14.0   
3        Positive            Positive                     2.0   
4        Positive            Positive                     3.0   

   Reginol_Node_Positive  Survival_Months Mortality_Status  
0                      1               60            Alive  
1                      5               62            Alive  
2                      7               75            Alive  
3                      1               84            Alive  
4                      1               50            Alive

In [6]:
#print column names of the dataset
list(df.columns)

['Patient_ID',
 'Month_of_Birth',
 'Age',
 'Sex',
 'Occupation',
 'T_Stage',
 'N_Stage',
 '6th_Stage',
 'Differentiated',
 'Grade',
 'A_Stage',
 'Tumor_Size',
 'Estrogen_Status',
 'Progesterone_Status',
 'Regional_Node_Examined',
 'Reginol_Node_Positive',
 'Survival_Months',
 'Mortality_Status']

In [7]:
#checking data formate
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4024 entries, 0 to 4023
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Patient_ID              4024 non-null   object 
 1   Month_of_Birth          4024 non-null   int64  
 2   Age                     4015 non-null   float64
 3   Sex                     4020 non-null   object 
 4   Occupation              43 non-null     object 
 5   T_Stage                 4024 non-null   object 
 6   N_Stage                 4024 non-null   object 
 7   6th_Stage               4024 non-null   object 
 8   Differentiated          4024 non-null   object 
 9   Grade                   4024 non-null   int64  
 10  A_Stage                 4024 non-null   object 
 11  Tumor_Size              4021 non-null   float64
 12  Estrogen_Status         4024 non-null   object 
 13  Progesterone_Status     4024 non-null   object 
 14  Regional_Node_Examined  4023 non-null   

In [8]:
#Anlayzing value errors
df.describe()

Month_of_Birth          Age        Grade   Tumor_Size  \
count     4024.000000  4015.000000  4024.000000  4021.000000   
mean         6.481362    54.107098     2.150596    30.419299   
std          3.475442    11.715528     0.638234    21.161080   
min          1.000000   -50.000000     1.000000   -75.000000   
25%          3.000000    47.000000     2.000000    16.000000   
50%          6.000000    54.000000     2.000000    25.000000   
75%         10.000000    61.000000     3.000000    38.000000   
max         12.000000   502.000000     4.000000   140.000000   

       Regional_Node_Examined  Reginol_Node_Positive  Survival_Months  
count             4023.000000            4024.000000      4024.000000  
mean                14.373602               4.158052        71.472167  
std                  8.129293               5.109331        25.361855  
min                  1.000000               1.000000         1.000000  
25%                  9.000000               1.000000        56.000000  
50%                 14.000000               2.000000        73.000000  
75%                 19.000000               5.000000        90.000000  
max                 61.000000              46.000000       760.000000

In [9]:
df.describe(include='object')

Patient_ID     Sex    Occupation T_Stage N_Stage 6th_Stage  \
count        4024    4020            43    4024    4024      4024   
unique       4024       2            40       4       3         5   
top         A0012  Female  House Person      T2      N1       IIA   
freq            1    4001             2    1786    2732      1305   

                   Differentiated   A_Stage Estrogen_Status  \
count                        4024      4024            4024   
unique                          4         2               2   
top     Moderately differentiated  Regional        Positive   
freq                         2351      3932            3755   

       Progesterone_Status Mortality_Status  
count                 4024             4024  
unique                   2                7  
top               Positive            Alive  
freq                  3326             3399

In [10]:
#dataset dimention
df.shape

(4024, 18)

In [11]:
#missing values in a column
df.isnull().sum()

Patient_ID                   0
Month_of_Birth               0
Age                          9
Sex                          4
Occupation                3981
T_Stage                      0
N_Stage                      0
6th_Stage                    0
Differentiated               0
Grade                        0
A_Stage                      0
Tumor_Size                   3
Estrogen_Status              0
Progesterone_Status          0
Regional_Node_Examined       1
Reginol_Node_Positive        0
Survival_Months              0
Mortality_Status             0
dtype: int64

In [12]:
#missing value in persentage
df.isnull().sum()/len(df)*100

Patient_ID                 0.000000
Month_of_Birth             0.000000
Age                        0.223658
Sex                        0.099404
Occupation                98.931412
T_Stage                    0.000000
N_Stage                    0.000000
6th_Stage                  0.000000
Differentiated             0.000000
Grade                      0.000000
A_Stage                    0.000000
Tumor_Size                 0.074553
Estrogen_Status            0.000000
Progesterone_Status        0.000000
Regional_Node_Examined     0.024851
Reginol_Node_Positive      0.000000
Survival_Months            0.000000
Mortality_Status           0.000000
dtype: float64

**Data Tranformation**

In [14]:
import pandas as pd
df = pd.read_csv('/5DATA002W.2 Coursework Dataset(25012025v6.0).csv')

**Handling Missing Values**

**Missing values are found under these features**
Regional_Node_Examined,
Tumor_Size,
Age,
Sex   

Handling missing values in SEX vaiable

In [15]:
df['Sex'].unique()

array(['Female', '1', nan], dtype=object)

In [16]:
# Replace '1' and any representations of missing values (nan, NaN, None) with 'Female'
df['Sex'] = df['Sex'].replace({1: 'Female', '1': 'Female', float('nan'): 'Female'})

# Convert the column to a consistent string type
df['Sex'] = df['Sex'].astype(str)

# Ensure all 'female' entries are standardized to 'Female'
df['Sex'] = df['Sex'].str.strip().str.lower().replace({'female': 'Female'})

Handling missing values in Regional_Node_Examined

In [17]:
df['Regional_Node_Examined'].unique()

array([24., 14.,  2.,  3., 18., 11.,  9., 20., 21., 13., 23., 16.,  1.,
       22., 15.,  4., 26., 31., 25., 10.,  5.,  6., 19., 12.,  8., 17.,
        7., 49., 33., 30., 34., 28., 32., 27., 42., 29., nan, 41., 39.,
       46., 40., 51., 44., 38., 47., 54., 36., 61., 60., 37., 35., 43.,
       52., 45., 57.])

Here using median value we replace the missing value in Regional_Node_Examined which is 41.

In [18]:
df['Regional_Node_Examined'].fillna(df['Regional_Node_Examined'].median(), inplace=True)
df['Regional_Node_Examined'].unique()

<ipython-input-18-d7f8fb602f8d>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Regional_Node_Examined'].fillna(df['Regional_Node_Examined'].median(), inplace=True)


array([24., 14.,  2.,  3., 18., 11.,  9., 20., 21., 13., 23., 16.,  1.,
       22., 15.,  4., 26., 31., 25., 10.,  5.,  6., 19., 12.,  8., 17.,
        7., 49., 33., 30., 34., 28., 32., 27., 42., 29., 41., 39., 46.,
       40., 51., 44., 38., 47., 54., 36., 61., 60., 37., 35., 43., 52.,
       45., 57.])

Handling missing values in Tumor_Size

In [19]:
df['Tumor_Size'].unique()

array([  4.,  35.,  63.,  18.,  41.,  20.,   8.,  30., 103.,  32.,  13.,
        59.,  15.,  19.,  46.,  24.,  25.,  29.,  40.,  70.,  22.,  50.,
        17.,  21.,  10.,  27.,  23.,   5.,  51.,   9.,  55., 120.,  77.,
         2.,  11.,  12.,  26.,  75., 130.,  34.,  80.,   3.,  60.,  14.,
        16.,  45.,  36.,  76.,  38.,  49.,   7.,  72., 100.,  43.,  62.,
        37.,  68., -75.,  52.,  85.,  57.,  39.,  28.,  48., 110.,  65.,
         6., 105., 140.,  42.,  31.,  90., 108.,  98.,  47.,  54.,  61.,
        74.,  33.,   1.,  87.,  nan,  81.,  58., 117.,  44., 123., 133.,
        95., 107.,  92.,  69.,  56.,  82.,  66.,  78.,  97.,  88.,  53.,
        83., 101.,  84., 115.,  73., 125., 104.,  94.,  86.,  64.,  96.,
        79.,  67.])

In [20]:
import numpy as np

In [21]:

# Calculate IQR
Q1 = df['Tumor_Size'].quantile(0.25)  # 25th percentile
Q3 = df['Tumor_Size'].quantile(0.75)  # 75th percentile
IQR = Q3 - Q1  # Interquartile range

# Define lower and upper bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

mean_value = df['Tumor_Size'].mean()
df['Tumor_Size'] = np.where(df['Tumor_Size'] < lower_bound, mean_value, df['Tumor_Size'])



In [22]:
print("Min:", df['Tumor_Size'].min())
print("Max:", df['Tumor_Size'].max())

Min: 1.0
Max: 140.0


Handling missing values in Age

In [23]:
df['Age'].unique()

array([ 68.,  50.,  58.,  47.,  51.,  40.,  69.,  46.,  65.,  48.,  62.,
        61.,  56.,  43.,  60.,  57.,  55.,  63.,  66.,  53.,  59.,  54.,
        49.,  64.,  42.,  nan,  37.,  67.,  31.,  52.,  33.,  45.,  38.,
        39.,  36., 180.,  41.,  44., -50.,  32.,  34., 502.,  35.,  30.,
        89.])

In [24]:
#Calculate IQR
Q1 = df['Age'].quantile(0.25)  # 25th percentile
Q3 = df['Age'].quantile(0.75)  # 75th percentile
IQR = Q3 - Q1  # Interquartile range

# Define lower and upper bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower Bound", lower_bound)
print("Upper Bound", upper_bound)
print('Age above Upper Bound : ' , len(df[df['Age'] > upper_bound]))
print('Age below Lower Bound : ' , len(df[df['Age'] < lower_bound]))

Lower Bound 26.0
Upper Bound 82.0
Age above Upper Bound :  3
Age below Lower Bound :  1


In [25]:
mean_value = df['Age'].mean()

#Replacing the outlier with mean value
df['Age'] = np.where(df['Age'] < lower_bound, mean_value, df['Age'])

#Replacing blank values with mean
df['Age'].fillna(df['Age'].median(), inplace=True)

print('Age below Lower Bound : ' , len(df[df['Age'] < lower_bound]))

Age below Lower Bound :  0


<ipython-input-25-83a6a76fefdd>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)


In [26]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

label_encoder = preprocessing.LabelEncoder()
df['Sex']= label_encoder.fit_transform(df['Sex'])

df['Sex'] = df['Sex'].replace({0: 1})
df.head()


Patient_ID  Month_of_Birth   Age  Sex   Occupation T_Stage N_Stage  \
0      A0012              12  68.0    1     Teaching      T1      N1   
1      A0013              12  50.0    1      Medical      T2      N2   
2      A0014              11  58.0    1  Engineering      T3      N3   
3      A0015               3  58.0    1   Technology      T1      N1   
4      A0016               1  47.0    1   Multimedia      T2      N1   

  6th_Stage             Differentiated  Grade   A_Stage  Tumor_Size  \
0       IIA      Poorly differentiated      3  Regional         4.0   
1      IIIA  Moderately differentiated      2  Regional        35.0   
2      IIIC  Moderately differentiated      2  Regional        63.0   
3       IIA      Poorly differentiated      3  Regional        18.0   
4       IIB      Poorly differentiated      3  Regional        41.0   

  Estrogen_Status Progesterone_Status  Regional_Node_Examined  \
0        Positive            Positive                    24.0   
1        Positive            Positive                    14.0   
2        Positive            Positive                    14.0   
3        Positive            Positive                     2.0   
4        Positive            Positive                     3.0   

   Reginol_Node_Positive  Survival_Months Mortality_Status  
0                      1               60            Alive  
1                      5               62            Alive  
2                      7               75            Alive  
3                      1               84            Alive  
4                      1               50            Alive

In [27]:
df['Sex'].unique()

array([1])

In [28]:
#Encoding occupation into numerical
df['Occupation'].unique()

array(['Teaching', 'Medical', 'Engineering', 'Technology', 'Multimedia',
       'Research', 'House Person', 'Reporting', 'Development',
       'Construction', 'Leisure', 'Scoial work', 'Trading', 'Consultancy',
       'Driving', 'Planning', 'Hospitality', 'Travel', 'Agriculture',
       'Manufacturing', 'Photography', 'Finance', 'Business', 'Marketing',
       'Training', 'Cleaning', 'Legal', 'Healthcare', 'Military', 'Sales',
       'Entertainment', 'Sports', 'Arts', 'Design', 'Maintenance',
       'Management', 'Human Resources', 'Administrative', 'Public',
       'Politics', nan], dtype=object)

In [29]:
# Fill the missing value with 'Occupation_1'
df['Occupation'] = df['Occupation'].fillna('Occupation_1')

In [30]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

label_encoder = preprocessing.LabelEncoder()
df['Occupation']= label_encoder.fit_transform(df['Occupation'])

df.head()

Patient_ID  Month_of_Birth   Age  Sex  Occupation T_Stage N_Stage 6th_Stage  \
0      A0012              12  68.0    1          36      T1      N1       IIA   
1      A0013              12  50.0    1          23      T2      N2      IIIA   
2      A0014              11  58.0    1          10      T3      N3      IIIC   
3      A0015               3  58.0    1          37      T1      N1       IIA   
4      A0016               1  47.0    1          25      T2      N1       IIB   

              Differentiated  Grade   A_Stage  Tumor_Size Estrogen_Status  \
0      Poorly differentiated      3  Regional         4.0        Positive   
1  Moderately differentiated      2  Regional        35.0        Positive   
2  Moderately differentiated      2  Regional        63.0        Positive   
3      Poorly differentiated      3  Regional        18.0        Positive   
4      Poorly differentiated      3  Regional        41.0        Positive   

  Progesterone_Status  Regional_Node_Examined  Reginol_Node_Positive  \
0            Positive                    24.0                      1   
1            Positive                    14.0                      5   
2            Positive                    14.0                      7   
3            Positive                     2.0                      1   
4            Positive                     3.0                      1   

   Survival_Months Mortality_Status  
0               60            Alive  
1               62            Alive  
2               75            Alive  
3               84            Alive  
4               50            Alive

In [31]:
#Encoding N_Stage into numerical
df['N_Stage'].unique()

array(['N1', 'N2', 'N3'], dtype=object)

In [32]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

label_encoder = preprocessing.LabelEncoder()
df['N_Stage']= label_encoder.fit_transform(df['N_Stage'])

df.head()

Patient_ID  Month_of_Birth   Age  Sex  Occupation T_Stage  N_Stage  \
0      A0012              12  68.0    1          36      T1        0   
1      A0013              12  50.0    1          23      T2        1   
2      A0014              11  58.0    1          10      T3        2   
3      A0015               3  58.0    1          37      T1        0   
4      A0016               1  47.0    1          25      T2        0   

  6th_Stage             Differentiated  Grade   A_Stage  Tumor_Size  \
0       IIA      Poorly differentiated      3  Regional         4.0   
1      IIIA  Moderately differentiated      2  Regional        35.0   
2      IIIC  Moderately differentiated      2  Regional        63.0   
3       IIA      Poorly differentiated      3  Regional        18.0   
4       IIB      Poorly differentiated      3  Regional        41.0   

  Estrogen_Status Progesterone_Status  Regional_Node_Examined  \
0        Positive            Positive                    24.0   
1        Positive            Positive                    14.0   
2        Positive            Positive                    14.0   
3        Positive            Positive                     2.0   
4        Positive            Positive                     3.0   

   Reginol_Node_Positive  Survival_Months Mortality_Status  
0                      1               60            Alive  
1                      5               62            Alive  
2                      7               75            Alive  
3                      1               84            Alive  
4                      1               50            Alive

In [33]:
#Encoding N_Stage into numerical
df['N_Stage'].unique()

array([0, 1, 2])

In [34]:
#Encoding T_Stage into numerical
df['T_Stage'].unique()

array(['T1', 'T2', 'T3', 'T4'], dtype=object)

In [35]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

label_encoder = preprocessing.LabelEncoder()
df['T_Stage']= label_encoder.fit_transform(df['T_Stage'])

df.head()

Patient_ID  Month_of_Birth   Age  Sex  Occupation  T_Stage  N_Stage  \
0      A0012              12  68.0    1          36        0        0   
1      A0013              12  50.0    1          23        1        1   
2      A0014              11  58.0    1          10        2        2   
3      A0015               3  58.0    1          37        0        0   
4      A0016               1  47.0    1          25        1        0   

  6th_Stage             Differentiated  Grade   A_Stage  Tumor_Size  \
0       IIA      Poorly differentiated      3  Regional         4.0   
1      IIIA  Moderately differentiated      2  Regional        35.0   
2      IIIC  Moderately differentiated      2  Regional        63.0   
3       IIA      Poorly differentiated      3  Regional        18.0   
4       IIB      Poorly differentiated      3  Regional        41.0   

  Estrogen_Status Progesterone_Status  Regional_Node_Examined  \
0        Positive            Positive                    24.0   
1        Positive            Positive                    14.0   
2        Positive            Positive                    14.0   
3        Positive            Positive                     2.0   
4        Positive            Positive                     3.0   

   Reginol_Node_Positive  Survival_Months Mortality_Status  
0                      1               60            Alive  
1                      5               62            Alive  
2                      7               75            Alive  
3                      1               84            Alive  
4                      1               50            Alive

In [36]:
#Encoding T_Stage into numerical
df['T_Stage'].unique()

array([0, 1, 2, 3])

In [37]:
#Encoding 6th_Stage into numerical
df['6th_Stage'].unique()

array(['IIA', 'IIIA', 'IIIC', 'IIB', 'IIIB'], dtype=object)

In [38]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

label_encoder = preprocessing.LabelEncoder()
df['6th_Stage']= label_encoder.fit_transform(df['6th_Stage'])

df.head()

Patient_ID  Month_of_Birth   Age  Sex  Occupation  T_Stage  N_Stage  \
0      A0012              12  68.0    1          36        0        0   
1      A0013              12  50.0    1          23        1        1   
2      A0014              11  58.0    1          10        2        2   
3      A0015               3  58.0    1          37        0        0   
4      A0016               1  47.0    1          25        1        0   

   6th_Stage             Differentiated  Grade   A_Stage  Tumor_Size  \
0          0      Poorly differentiated      3  Regional         4.0   
1          2  Moderately differentiated      2  Regional        35.0   
2          4  Moderately differentiated      2  Regional        63.0   
3          0      Poorly differentiated      3  Regional        18.0   
4          1      Poorly differentiated      3  Regional        41.0   

  Estrogen_Status Progesterone_Status  Regional_Node_Examined  \
0        Positive            Positive                    24.0   
1        Positive            Positive                    14.0   
2        Positive            Positive                    14.0   
3        Positive            Positive                     2.0   
4        Positive            Positive                     3.0   

   Reginol_Node_Positive  Survival_Months Mortality_Status  
0                      1               60            Alive  
1                      5               62            Alive  
2                      7               75            Alive  
3                      1               84            Alive  
4                      1               50            Alive

In [39]:
#Encoding 6th_Stage into numerical
df['6th_Stage'].unique()

array([0, 2, 4, 1, 3])

In [40]:
#Encoding Differentiated into numerical
df['Differentiated'].unique()

array(['Poorly differentiated', 'Moderately differentiated',
       'Well differentiated', 'Undifferentiated'], dtype=object)

In [41]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

label_encoder = preprocessing.LabelEncoder()
df['Differentiated']= label_encoder.fit_transform(df['Differentiated'])

df.head()

Patient_ID  Month_of_Birth   Age  Sex  Occupation  T_Stage  N_Stage  \
0      A0012              12  68.0    1          36        0        0   
1      A0013              12  50.0    1          23        1        1   
2      A0014              11  58.0    1          10        2        2   
3      A0015               3  58.0    1          37        0        0   
4      A0016               1  47.0    1          25        1        0   

   6th_Stage  Differentiated  Grade   A_Stage  Tumor_Size Estrogen_Status  \
0          0               1      3  Regional         4.0        Positive   
1          2               0      2  Regional        35.0        Positive   
2          4               0      2  Regional        63.0        Positive   
3          0               1      3  Regional        18.0        Positive   
4          1               1      3  Regional        41.0        Positive   

  Progesterone_Status  Regional_Node_Examined  Reginol_Node_Positive  \
0            Positive                    24.0                      1   
1            Positive                    14.0                      5   
2            Positive                    14.0                      7   
3            Positive                     2.0                      1   
4            Positive                     3.0                      1   

   Survival_Months Mortality_Status  
0               60            Alive  
1               62            Alive  
2               75            Alive  
3               84            Alive  
4               50            Alive

In [42]:
#Encoding Differentiated into numerical
df['Differentiated'].unique()

array([1, 0, 3, 2])

In [43]:
#Encoding A_Stage into numerical
df['A_Stage'].unique()

array(['Regional', 'Distant'], dtype=object)

In [44]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

label_encoder = preprocessing.LabelEncoder()
df['A_Stage']= label_encoder.fit_transform(df['A_Stage'])

df.head()

Patient_ID  Month_of_Birth   Age  Sex  Occupation  T_Stage  N_Stage  \
0      A0012              12  68.0    1          36        0        0   
1      A0013              12  50.0    1          23        1        1   
2      A0014              11  58.0    1          10        2        2   
3      A0015               3  58.0    1          37        0        0   
4      A0016               1  47.0    1          25        1        0   

   6th_Stage  Differentiated  Grade  A_Stage  Tumor_Size Estrogen_Status  \
0          0               1      3        1         4.0        Positive   
1          2               0      2        1        35.0        Positive   
2          4               0      2        1        63.0        Positive   
3          0               1      3        1        18.0        Positive   
4          1               1      3        1        41.0        Positive   

  Progesterone_Status  Regional_Node_Examined  Reginol_Node_Positive  \
0            Positive                    24.0                      1   
1            Positive                    14.0                      5   
2            Positive                    14.0                      7   
3            Positive                     2.0                      1   
4            Positive                     3.0                      1   

   Survival_Months Mortality_Status  
0               60            Alive  
1               62            Alive  
2               75            Alive  
3               84            Alive  
4               50            Alive

In [45]:
#Encoding A_Stage into numerical
df['A_Stage'].unique()

array([1, 0])

In [46]:
#Encoding Estrogen_Status into numerical
df['Estrogen_Status'].unique()

array(['Positive', 'Negative'], dtype=object)

In [47]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

label_encoder = preprocessing.LabelEncoder()
df['Estrogen_Status']= label_encoder.fit_transform(df['Estrogen_Status'])

df.head()

Patient_ID  Month_of_Birth   Age  Sex  Occupation  T_Stage  N_Stage  \
0      A0012              12  68.0    1          36        0        0   
1      A0013              12  50.0    1          23        1        1   
2      A0014              11  58.0    1          10        2        2   
3      A0015               3  58.0    1          37        0        0   
4      A0016               1  47.0    1          25        1        0   

   6th_Stage  Differentiated  Grade  A_Stage  Tumor_Size  Estrogen_Status  \
0          0               1      3        1         4.0                1   
1          2               0      2        1        35.0                1   
2          4               0      2        1        63.0                1   
3          0               1      3        1        18.0                1   
4          1               1      3        1        41.0                1   

  Progesterone_Status  Regional_Node_Examined  Reginol_Node_Positive  \
0            Positive                    24.0                      1   
1            Positive                    14.0                      5   
2            Positive                    14.0                      7   
3            Positive                     2.0                      1   
4            Positive                     3.0                      1   

   Survival_Months Mortality_Status  
0               60            Alive  
1               62            Alive  
2               75            Alive  
3               84            Alive  
4               50            Alive

In [48]:
#Encoding Estrogen_Status into numerical
df['Estrogen_Status'].unique()

array([1, 0])

In [ ]:
#Encoding Progesterone_Status into numerical
df['Progesterone_Status'].unique()

array(['Positive', 'Negative'], dtype=object)

In [49]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

label_encoder = preprocessing.LabelEncoder()
df['Progesterone_Status']= label_encoder.fit_transform(df['Progesterone_Status'])

df.head()

Patient_ID  Month_of_Birth   Age  Sex  Occupation  T_Stage  N_Stage  \
0      A0012              12  68.0    1          36        0        0   
1      A0013              12  50.0    1          23        1        1   
2      A0014              11  58.0    1          10        2        2   
3      A0015               3  58.0    1          37        0        0   
4      A0016               1  47.0    1          25        1        0   

   6th_Stage  Differentiated  Grade  A_Stage  Tumor_Size  Estrogen_Status  \
0          0               1      3        1         4.0                1   
1          2               0      2        1        35.0                1   
2          4               0      2        1        63.0                1   
3          0               1      3        1        18.0                1   
4          1               1      3        1        41.0                1   

   Progesterone_Status  Regional_Node_Examined  Reginol_Node_Positive  \
0                    1                    24.0                      1   
1                    1                    14.0                      5   
2                    1                    14.0                      7   
3                    1                     2.0                      1   
4                    1                     3.0                      1   

   Survival_Months Mortality_Status  
0               60            Alive  
1               62            Alive  
2               75            Alive  
3               84            Alive  
4               50            Alive

In [50]:
#Encoding Progesterone_Status into numerical
df['Progesterone_Status'].unique()

array([1, 0])

In [51]:
#Encoding Mortality_Status into numerical
df['Mortality_Status'].unique()

array(['Alive', 'Dead', 'ALIVE', 'DEAD', 'ALive', 'alive', 'dead'],
      dtype=object)

In [52]:
# Standardize the 'Mortality_Status' column
df['Mortality_Status'] = df['Mortality_Status'].str.strip().str.lower().replace({
    'alive': 'Alive',
    'dead': 'Dead'
})
# Convert the column to a consistent string type
df['Mortality_Status'] = df['Mortality_Status'].astype(str)

In [53]:
df['Mortality_Status'].unique()

array(['Alive', 'Dead'], dtype=object)

In [54]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

label_encoder = preprocessing.LabelEncoder()
df['Mortality_Status']= label_encoder.fit_transform(df['Mortality_Status'])

df.head()

Patient_ID  Month_of_Birth   Age  Sex  Occupation  T_Stage  N_Stage  \
0      A0012              12  68.0    1          36        0        0   
1      A0013              12  50.0    1          23        1        1   
2      A0014              11  58.0    1          10        2        2   
3      A0015               3  58.0    1          37        0        0   
4      A0016               1  47.0    1          25        1        0   

   6th_Stage  Differentiated  Grade  A_Stage  Tumor_Size  Estrogen_Status  \
0          0               1      3        1         4.0                1   
1          2               0      2        1        35.0                1   
2          4               0      2        1        63.0                1   
3          0               1      3        1        18.0                1   
4          1               1      3        1        41.0                1   

   Progesterone_Status  Regional_Node_Examined  Reginol_Node_Positive  \
0                    1                    24.0                      1   
1                    1                    14.0                      5   
2                    1                    14.0                      7   
3                    1                     2.0                      1   
4                    1                     3.0                      1   

   Survival_Months  Mortality_Status  
0               60                 0  
1               62                 0  
2               75                 0  
3               84                 0  
4               50                 0

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4024 entries, 0 to 4023
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Patient_ID              4024 non-null   object 
 1   Month_of_Birth          4024 non-null   int64  
 2   Age                     4024 non-null   float64
 3   Sex                     4024 non-null   int64  
 4   Occupation              4024 non-null   int64  
 5   T_Stage                 4024 non-null   int64  
 6   N_Stage                 4024 non-null   int64  
 7   6th_Stage               4024 non-null   int64  
 8   Differentiated          4024 non-null   int64  
 9   Grade                   4024 non-null   int64  
 10  A_Stage                 4024 non-null   int64  
 11  Tumor_Size              4021 non-null   float64
 12  Estrogen_Status         4024 non-null   int64  
 13  Progesterone_Status     4024 non-null   int64  
 14  Regional_Node_Examined  4024 non-null   